name: Generate HTML from JSON data

on: [push]

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Install deps
      run: npm install
    - name: Generate index.html
      run: npm run gen
    - name: Commit and push
      run: |
        git add index.html
        git commit -m "Generate index.html"
        git push github HEAD:${GITHUB_REF}
        

